# Copyright (c) 2026 Mike Grier

[package]
name          = "msbuild-diagnostic"
description   = "Tools to help work with msbuild based project builds to diagnose and correct bad behaviors"
readme        = "README.md"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
repository.workspace    = true
homepage.workspace      = true
documentation.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
gethostname = "1.1.0"
munin-msbuild = "0.3.1"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2 = "0.11.0"
time = { version = "0.3.47", features = ["formatting"] }
zip = { version = "8", default-features = false, features = ["deflate-flate2"] }

[dev-dependencies]
base64 = "0.22.1"
tempfile = "3.27.0"
