# Copyright (c) 2026 Mike Grier

[package]
name          = "msbuild-diagnostic"
description   = "Tools to help work with msbuild based project builds to diagnose and correct bad behaviors"
readme        = "README.md"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
repository.workspace    = true
homepage.workspace      = true
documentation.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
munin-msbuild = "0.3.1"

[dev-dependencies]
